# Generated by Django 2.1.1 on 2019-11-05 18:00

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.FileField(default=None, upload_to=utils.upload.profile_image_path, validators=[utils.validators.profile_image_size, utils.validators.profile_image_extension]),
        ),
    ]
